Added support for custom item shapes
lukepighetti/salomon_bottom_bar pull request #7
Opened 2021-06-16 13:21 UTC by EriKWDev

This PR adds support for custom item shapes other than just StadiumBorder.
It can be specified per item or for all items. Mimicking the behaviour of the other parameters, the shape specified on each item takes priority over the shape defined for that BottomBar.

Example shape could be
```dart
RoundedRectangleBorder(
  borderRadius: BorderRadius.circular(10)
)
```

2021-06-16 13:30 UTC, EriKWDev commented
### Preview of custom shape
![Screenshot 2021-06-16 at 15 28 14](https://user-images.githubusercontent.com/19771356/122227764-7ad44200-ceb7-11eb-848a-26d36ae0c0db.png)

```dart
...
SalomonBottomBarItem(
  shape: RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(10)
  ),
  icon: const Icon(Icons.home_outlined),
  title: const Text("Home"),
),
...
```
or
```dart
...
SalomonBottomBar(
  itemShape: RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(10)
   ),
  currentIndex: _currentIndex,
  onTap: (i) => setState(() => _currentIndex = i),
  items: [
...
```

2021-06-17 12:19 UTC, lukepighetti requested changes
Hi Erik, normally I wouldn't merge this because it's outside the dribble spec, and the package is a one-pager so it's easy to copy-paste and modify (I highly recommend it, this package is quite stable). 

However, exposing the global shape seems reasonable to me. 

I don't feel comfortable having this settable at the item level though, so if we can remove that then I'd be happy to review it again.

2021-06-17 12:19 UTC, lukepighetti commented on lib/salomon_bottom_bar.dart
> +    this.shape,
```suggestion
```

2021-06-17 12:19 UTC, lukepighetti commented on lib/salomon_bottom_bar.dart
> +
```suggestion
```

2021-06-17 12:19 UTC, lukepighetti commented on lib/salomon_bottom_bar.dart
> +                    customBorder: _itemShape,
```suggestion
                    customBorder: itemShape,
```

2021-06-17 12:19 UTC, lukepighetti commented on lib/salomon_bottom_bar.dart
> +                  shape: _itemShape,
```suggestion
                  shape: itemShape,
```

2021-06-17 12:19 UTC, lukepighetti commented on lib/salomon_bottom_bar.dart
> +
```suggestion
```

2021-06-17 12:53 UTC, EriKWDev commented
Sure thing! I was a bit unsure wether to create a PR or not since I read that we should only do so if it doesn't conform to the spec, but I thought this could be a small and useful customisation for anyone wanting to use it :)

I agree it might be weird to have different shapes per item, but added it just in case. The global shape for every item is all I needed for my purposes. I'll fix it!

2021-06-17 14:02 UTC, lukepighetti approved these changes
LGTM. Thanks for the fast followup.

2021-06-17 14:02 UTC, merged